[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
via_ir = true  # Required for snarkjs-generated verifier with 4 public signals

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[invariant]
runs = 256           # Number of invariant test runs
depth = 15          # Number of calls per run
fail_on_revert = false  # Don't fail if handler functions revert
